### ISSUE TITLE
As a Perfomer, I want to be able to list any food allergies without having to select paying for food

### ISSUE THREAD

**Issue by pelololoquin** [magfest/bands#42] opened 2016-06-08 16:15 UTC
Currently, the food allergies section only shows up when you select paying for food.  Since bands are not paying fro food, they will not be clicking the checkbox, so allergies/restrictions does not show up for them.  

The way it should work is all badges linked to a band should have the text fill option for food restrictions/allergies instead of the food payment section

**Comment by pelololoquin** [comment] 2016-06-08 16:17
![image](https://cloud.githubusercontent.com/assets/7318559/15901809/e9f0d3ce-2d72-11e6-9f41-773b76db5a7d.png)

![image](https://cloud.githubusercontent.com/assets/7318559/15901823/f8a4a97c-2d72-11e6-9966-56bb05184db5.png)

**Comment by pelololoquin** [comment] 2016-06-08 16:18
This should be the field that shows
![image](https://cloud.githubusercontent.com/assets/7318559/15901862/2704ecc8-2d73-11e6-8991-16baf229b14f.png)

**Comment by binary1230** [comment] 2016-06-08 16:27
There's some logic that shows/hides this field based on whether you're receiving food, maybe best to have uber check this box for performers and comps (without them being asked to pay for it), and let the rest of the logic stand as-is.

lemme look into it, 1s

**Comment by binary1230** [comment] 2016-06-08 16:31
ok maybe a better way, uber determines if you automatically get food based on:

```
@property
    def auto_food(self):
        return self.badge_type in [c.STAFF_BADGE, c.GUEST_BADGE]
```

+1's of bands are attendee badges so not in this list, however, we could probably check there via an override if this attendee is part of a group that is part of a band, and if so, they auto-get food.

**Comment by pelololoquin** [comment] 2016-06-08 16:33
as long as the $20 isn't on the page for claiming the badges.  Otherwise we'll get another person paying for food who doesn't need to or a group getting confused/upset about paying for food we said was included.

**Comment by kitsuta** [comment] 2016-06-09 06:09
Closing as a duplicate of https://github.com/magfest/magstock/issues/74.

I will file an issue in the magprime plugin to make sure we don't overlook this for bands in that event, but this is ultimately different per event (e.g., there's no option to buy food for Prime and allergies are collected in a different way).

**Closed by kitsuta** 2016-06-09 06:09 UTC
